<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Church;
use App\Models\Event;
use App\Models\GalleryItem;
use App\Models\Sermon;
use App\Models\Resource;
use App\Models\Testimonial;
use App\Models\Leadership;
use App\Models\Partner;
use App\Models\Post;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $this->call(ContentSectionSeeder::class);
        if (!User::where('email', 'admin@wccf.ug')->exists()) {
            User::factory()->create([
                'name' => 'Admin User',
                'email' => 'admin@wccf.ug',
            ]);
        }

        Church::create(['name' => 'Arua Cathedral Church', 'slug' => 'arua-cathedral', 'region' => 'West Nile', 'district' => 'Arua', 'pastor_name' => 'Rev. John Doe', 'phone' => '+256-700-000001', 'description' => 'A vibrant Anglican community serving Arua.', 'is_active' => true]);
        Church::create(['name' => 'Kampala International Church', 'slug' => 'kampala-international', 'region' => 'Buganda', 'district' => 'Kampala', 'pastor_name' => 'Pastor Samuel K.', 'phone' => '+256-700-000002', 'description' => 'Multi-denominational fellowship.', 'is_active' => true]);
        Church::create(['name' => 'Jinja Christian Centre', 'slug' => 'jinja-christian-centre', 'region' => 'Busoga', 'district' => 'Jinja', 'pastor_name' => 'Rev. Sarah M.', 'phone' => '+256-700-000003', 'description' => 'Spreading the gospel in Jinja.', 'is_active' => true]);
        Church::create(['name' => 'Hoima Baptist Church', 'slug' => 'hoima-baptist', 'region' => 'Bunyoro', 'district' => 'Hoima', 'pastor_name' => 'Pastor David O.', 'phone' => '+256-700-000004', 'description' => 'Baptist fellowship in Bunyoro.', 'is_active' => true]);
        Church::create(['name' => 'Gulu Redeemed Church', 'slug' => 'gulu-redeemed', 'region' => 'West Nile', 'district' => 'Gulu', 'pastor_name' => 'Rev. Peter L.', 'phone' => '+256-700-000005', 'description' => 'Redeemed Christian fellowship.', 'is_active' => true]);
        Church::create(['name' => 'Mbale Worship Centre', 'slug' => 'mbale-worship', 'region' => 'Busoga', 'district' => 'Mbale', 'pastor_name' => 'Pastor Grace A.', 'phone' => '+256-700-000006', 'description' => 'Worship and fellowship centre.', 'is_active' => true]);

        Event::create(['title' => 'Annual WCCF Fellowship Conference 2026', 'slug' => 'annual-fellowship-2026', 'type' => 'conference', 'description' => 'Join us for our annual gathering with over 70 member churches.', 'event_date' => '2026-08-15', 'event_time' => '09:00', 'location' => 'Arua City Hall', 'is_featured' => true, 'is_active' => true]);
        Event::create(['title' => 'Regional Prayer and Worship Summit', 'slug' => 'prayer-worship-summit', 'type' => 'workshop', 'description' => 'A powerful time of prayer and worship.', 'event_date' => '2026-07-20', 'event_time' => '10:00', 'location' => 'Kampala', 'is_featured' => true, 'is_active' => true]);
        Event::create(['title' => 'Community Outreach Program', 'slug' => 'community-outreach-2026', 'type' => 'outreach', 'description' => 'Serving communities across West Nile.', 'event_date' => '2026-09-10', 'event_time' => '08:00', 'location' => 'Various Locations', 'is_featured' => true, 'is_active' => true]);
        Event::create(['title' => 'Youth Fellowship Retreat', 'slug' => 'youth-retreat-2026', 'type' => 'fellowship', 'description' => 'Annual youth retreat for spiritual growth.', 'event_date' => '2026-06-25', 'event_time' => '14:00', 'location' => 'Gulu', 'is_active' => true]);
        Event::create(['title' => 'Leadership Training Workshop', 'slug' => 'leadership-training-2026', 'type' => 'workshop', 'description' => 'Equipping church leaders for effective ministry.', 'event_date' => '2026-10-05', 'event_time' => '09:00', 'location' => 'Arua', 'is_active' => true]);
        Event::create(['title' => 'Christmas Fellowship Gathering', 'slug' => 'christmas-fellowship-2026', 'type' => 'fellowship', 'description' => 'Celebrating the birth of our Lord together.', 'event_date' => '2026-12-25', 'event_time' => '10:00', 'location' => 'All Member Churches', 'is_active' => true]);

        Testimonial::create(['name' => 'Bishop John O.', 'position' => 'Chairman', 'organization' => 'WCCF', 'content' => 'WCCF has been instrumental in uniting churches across West Nile. Together we are making a greater impact for the Kingdom of God.', 'rating' => 5, 'sort_order' => 1, 'is_active' => true]);
        Testimonial::create(['name' => 'Rev. Sarah M.', 'position' => 'Lead Pastor', 'organization' => 'Arua Cathedral', 'content' => 'Being part of WCCF has strengthened our church and expanded our reach in the community. The fellowship is truly blessed.', 'rating' => 5, 'sort_order' => 2, 'is_active' => true]);
        Testimonial::create(['name' => 'Pastor David O.', 'position' => 'Regional Coordinator', 'organization' => 'Bunyoro Region', 'content' => 'The conferences and workshops organized by WCCF have equipped our leaders and transformed our approach to ministry.', 'rating' => 5, 'sort_order' => 3, 'is_active' => true]);

        Leadership::create(['name' => 'Bishop John Doe', 'position' => 'Chairman', 'bio' => 'Providing spiritual oversight and strategic direction.', 'sort_order' => 1, 'is_active' => true]);
        Leadership::create(['name' => 'Rev. Jane Smith', 'position' => 'Vice Chairperson', 'bio' => 'Coordinating fellowship activities and supporting member churches.', 'sort_order' => 2, 'is_active' => true]);
        Leadership::create(['name' => 'Pastor Samuel O.', 'position' => 'General Secretary', 'bio' => 'Managing day-to-day operations and administrative functions.', 'sort_order' => 3, 'is_active' => true]);

        Partner::create(['name' => 'Uganda Christian University', 'logo' => 'https://placehold.co/200x80/5f0138/fff?text=UCU', 'website' => '#', 'sort_order' => 1, 'is_active' => true]);
        Partner::create(['name' => 'Arua Diocese', 'logo' => 'https://placehold.co/200x80/D4AF37/000?text=Arua', 'website' => '#', 'sort_order' => 2, 'is_active' => true]);
        Partner::create(['name' => 'Born Again Faith', 'logo' => 'https://placehold.co/200x80/5f0138/fff?text=BAF', 'website' => '#', 'sort_order' => 3, 'is_active' => true]);
        Partner::create(['name' => 'Uganda Fellowship', 'logo' => 'https://placehold.co/200x80/D4AF37/000?text=UFF', 'website' => '#', 'sort_order' => 4, 'is_active' => true]);
        Partner::create(['name' => 'West Nile Diocese', 'logo' => 'https://placehold.co/200x80/430027/fff?text=WND', 'website' => '#', 'sort_order' => 5, 'is_active' => true]);
        Partner::create(['name' => 'Christian Aid Uganda', 'logo' => 'https://placehold.co/200x80/5f0138/fff?text=CAU', 'website' => '#', 'sort_order' => 6, 'is_active' => true]);

        Resource::create(['title' => 'The Power of United Prayer', 'slug' => 'power-of-united-prayer', 'type' => 'sermon', 'description' => 'A sermon on the power of united prayer among believers.', 'is_active' => true]);
        Resource::create(['title' => 'Biblical Leadership Principles', 'slug' => 'biblical-leadership', 'type' => 'teaching', 'description' => 'Teaching resource on biblical leadership for church leaders.', 'is_active' => true]);
        Resource::create(['title' => 'Book of Romans Study Guide', 'slug' => 'romans-study-guide', 'type' => 'bible_study', 'description' => 'A comprehensive study guide through the book of Romans.', 'is_active' => true]);
        Resource::create(['title' => 'Conference Proceedings 2025', 'slug' => 'conference-2025-proceedings', 'type' => 'conference_material', 'description' => 'Proceedings from the 2025 annual fellowship conference.', 'is_active' => true]);

        GalleryItem::create(['title' => 'Annual Conference 2025', 'slug' => 'conference-2025', 'category' => 'conferences', 'image' => 'https://placehold.co/800x600/5f0138/fff?text=Conference+2025', 'sort_order' => 1, 'is_active' => true]);
        GalleryItem::create(['title' => 'Sunday Worship Service', 'slug' => 'worship-service-1', 'category' => 'worship', 'image' => 'https://placehold.co/800x600/430027/ff0?text=Worship', 'sort_order' => 2, 'is_active' => true]);
        GalleryItem::create(['title' => 'Community Outreach Day', 'slug' => 'outreach-day-1', 'category' => 'outreach', 'image' => 'https://placehold.co/800x600/D4AF37/000?text=Outreach', 'sort_order' => 3, 'is_active' => true]);
        GalleryItem::create(['title' => 'Fellowship Gathering', 'slug' => 'fellowship-1', 'category' => 'fellowship', 'image' => 'https://placehold.co/600x800/5f0138/fff?text=Fellowship', 'sort_order' => 4, 'is_active' => true]);
        GalleryItem::create(['title' => 'Church Leaders Meeting', 'slug' => 'leaders-meeting-1', 'category' => 'gatherings', 'image' => 'https://placehold.co/800x600/430027/ff0?text=Leaders', 'sort_order' => 5, 'is_active' => true]);
        GalleryItem::create(['title' => 'Youth Worship Night', 'slug' => 'youth-worship-1', 'category' => 'worship', 'image' => 'https://placehold.co/600x800/D4AF37/000?text=Youth', 'sort_order' => 6, 'is_active' => true]);

        Sermon::create(['title' => 'Unity in the Body of Christ', 'slug' => 'unity-in-christ', 'speaker' => 'Bishop John Doe', 'description' => 'A sermon on the importance of unity among believers.', 'sermon_date' => '2026-01-15', 'is_active' => true]);
        Sermon::create(['title' => 'The Power of Prayer', 'slug' => 'power-of-prayer', 'speaker' => 'Rev. Jane Smith', 'description' => 'Understanding the transformative power of prayer.', 'sermon_date' => '2026-02-20', 'is_active' => true]);

        Post::create(['title' => 'Mega Church Project Officially Launched', 'slug' => 'mega-church-project-launched', 'content' => "We are overjoyed to announce the official launch of the WCCF Mega Church Building Project! After decades of praying and planning, we have taken the first step toward building a permanent home for worship, fellowship, and community transformation in the West Nile region.\n\nThe vision for this project was born out of a simple but profound need: for over 35 years, WCCF has united over 70 member churches without a central house of worship. While our fellowship has grown and flourished, we have long dreamed of a place where all believers can gather under one roof.\n\nOn March 15, 2026, during a historic ceremony attended by church leaders, government officials, and community members from across the region, we officially broke ground on the mega church site in Arua City. The event was marked by worship, prayer, and a powerful sense of God's presence.\n\nBishop John Doe, WCCF Chairman, addressed the gathering: 'This is not just about building a structure. It is about building a spiritual home for thousands of believers. It is about leaving a legacy of faith for our children and grandchildren. It is about declaring that God is alive and at work in West Nile.'\n\nThe mega church will feature a 5,000-seat sanctuary, a community center, a leadership training facility, a prayer tower, and administrative offices. The total project cost is estimated at UGX 5 billion.\n\nWe invite all believers, churches, and partners to join us in this historic undertaking. Whether through prayer, financial giving, or spreading the word, every contribution brings us closer to seeing this vision become a reality.\n\nTo God be all the glory — great things He has done!", 'excerpt' => 'WCCF officially launches the mega church building project with a groundbreaking ceremony in Arua City.', 'author' => 'WCCF Communications', 'category' => 'project-update', 'featured_image' => 'images/image-01.jpg', 'published_at' => '2026-03-16 09:00:00', 'is_featured' => true, 'is_active' => true]);
        Post::create(['title' => 'First Phase of Construction Begins', 'slug' => 'first-phase-construction-begins', 'content' => "We are thrilled to announce that the first phase of construction for the WCCF Mega Church has officially begun! After months of planning, fundraising, and preparation, we have broken ground on the site and commenced foundation work.\n\nThe first phase includes:\n\n1. Site clearing and leveling - Complete\n2. Foundation excavation - In progress\n3. Concrete foundation pouring - Scheduled for next month\n4. Main sanctuary structural framework\n5. Perimeter wall and security infrastructure\n\n'Seeing the excavators on site is a powerful reminder that God is faithful,' said Pastor Samuel O., General Secretary of WCCF. 'For years we prayed for this day, and now it is here. We give God all the glory.'\n\nThe construction is being undertaken by God's Grace Construction Ltd, a reputable firm with extensive experience in large-scale church projects across East Africa. The project manager, Eng. James Okello, assured the leadership that the work will meet the highest standards of quality and safety.\n\n'We are using reinforced concrete and steel-frame construction to ensure the building stands for generations,' Eng. Okello explained. 'The sanctuary alone will require over 2,000 tons of concrete and 300 tons of steel reinforcement.'\n\nThe first phase is expected to be completed within 12 months, at which point we will begin the interior finishing and furnishing phases.\n\nWe continue to appeal for financial support to sustain the construction momentum. The building fund currently stands at UGX 500 million, representing 10% of our UGX 5 billion target. Every contribution, whether large or small, makes a difference.\n\nTo give, visit our donate page or use the bank details below. Thank you for being part of this historic journey.", 'excerpt' => 'Foundation work begins on the 5,000-seat mega church sanctuary in Arua.', 'author' => 'Eng. James Okello', 'category' => 'project-update', 'featured_image' => 'images/image-02.jpg', 'published_at' => '2026-04-20 10:00:00', 'is_featured' => true, 'is_active' => true]);
        Post::create(['title' => 'WCCF Holds First Fundraising Gala', 'slug' => 'fundraising-gala-recap', 'content' => "On the evening of April 25, 2026, WCCF held its inaugural Mega Church Fundraising Gala at the Arua City Convention Centre. The event was a resounding success, bringing together over 300 guests including church leaders, business professionals, government officials, and international partners.\n\nThe black-tie gala featured worship performances by the combined WCCF choir, a keynote address by Bishop John Doe, and a moving testimony from a long-time member about what the mega church will mean for future generations.\n\n'This is a generational moment,' Bishop Doe said in his address. 'What we build today will be a blessing not just for us, but for our children and our children's children. Let us give generously and joyfully.'\n\nHighlights of the evening included:\n- A live fundraising auction that raised UGX 45 million\n- Pledge cards totaling UGX 120 million in committed donations\n- Several churches committing to monthly partnership contributions\n- International partners pledging technical and financial support\n\n'We were overwhelmed by the generosity of everyone who attended,' said Rev. Jane Smith, Vice Chairperson of WCCF. 'The body of Christ has truly come together to support this vision.'\n\nThe gala also served as an opportunity to update partners on the construction progress. Attendees were shown architectural renderings of the completed sanctuary and community center.\n\nWe extend our heartfelt gratitude to everyone who attended, donated, and prayed. If you were unable to attend but would still like to contribute, please visit our donate page or contact our offices.", 'excerpt' => 'WCCF raises over UGX 165 million at the first mega church fundraising gala.', 'author' => 'WCCF Communications', 'category' => 'news', 'featured_image' => 'images/image-03.jpg', 'published_at' => '2026-04-28 14:00:00', 'is_featured' => true, 'is_active' => true]);
        Post::create(['title' => 'Community Outreach Day a Huge Success', 'slug' => 'community-outreach-success', 'content' => "On Saturday, May 10, 2026, WCCF organized a major community outreach and medical camp in the areas surrounding the new mega church construction site. The event was part of our commitment to serve the community even as we build.\n\nOver 500 local residents benefited from the free services provided:\n\n- General medical consultations: 320 patients treated\n- Malaria testing and treatment: 180 cases\n- Blood pressure and diabetes screening: 250 people\n- Children's immunization: 60 children vaccinated\n- Free mosquito nets distributed: 200 nets\n\nIn addition to medical services, we also distributed food supplies and clothing to vulnerable families in the community. The WCCF prayer team was on hand to pray with individuals and families.\n\n'This is what the love of Christ looks like in action,' said Pastor David O., who coordinated the outreach. 'We are not just building a church building; we are building relationships and demonstrating God's love to our community.'\n\nThe outreach was supported by medical volunteers from Arua Regional Referral Hospital and funding from partner churches. We plan to hold similar outreaches quarterly throughout the construction period.\n\nIf you would like to support our next outreach event, please contact our offices or make a donation designated for community outreach.", 'excerpt' => 'Over 500 community members receive free medical care and supplies during WCCF outreach event.', 'author' => 'Pastor David O.', 'category' => 'news', 'featured_image' => 'images/image-04.jpg', 'published_at' => '2026-05-12 11:00:00', 'is_featured' => false, 'is_active' => true]);
        Post::create(['title' => 'Monthly Partner Program Launched', 'slug' => 'monthly-partner-program', 'content' => "We are excited to announce the launch of the WCCF Mega Church Monthly Partner Program! This initiative invites individuals, families, and churches to commit to a recurring monthly donation that will provide stable, predictable funding for the building project.\n\nWhy become a monthly partner? Consistent monthly giving allows us to plan construction phases with confidence. Knowing that a certain amount will come in each month enables us to commit to contractors, order materials in advance, and avoid costly delays.\n\nMonthly partners will receive:\n- Regular construction progress updates with photos\n- Exclusive partner prayer meetings (quarterly)\n- Recognition in the WCCF partners' wall\n- Invitations to special site visits and events\n- Annual partner appreciation gathering\n\n'We are inviting 1,000 faithful partners to commit to a monthly gift of UGX 100,000 or more,' said Bishop Doe. 'If 1,000 people give UGX 100,000 per month, that is UGX 100 million in monthly recurring support — enough to sustain construction at full pace.'\n\nTo join the Monthly Partner Program, visit our donate page and select the 'Monthly Partner' option. You can set up a standing order at any Stanbic Bank branch or give online.\n\nJoin us as a monthly partner and be part of this historic work of faith!", 'excerpt' => 'WCCF launches a monthly giving program inviting 1,000 partners to sustain construction.', 'author' => 'WCCF Communications', 'category' => 'project-update', 'featured_image' => 'images/image-05.jpg', 'published_at' => '2026-05-20 08:00:00', 'is_featured' => true, 'is_active' => true]);
        Post::create(['title' => 'Youth Fellowship Organizes Prayer Walk for Construction', 'slug' => 'youth-prayer-walk', 'content' => "On Saturday, June 1, 2026, over 200 young people from WCCF member churches gathered for a prayer walk around the mega church construction site. The event was organized by the WCCF Youth Fellowship as part of their commitment to covering the project in prayer.\n\nThe youth, carrying banners and singing worship songs, walked a 3-kilometer route around the site perimeter, stopping at designated points to pray for:\n\n- The safety of construction workers\n- God's provision for the building fund\n- The spiritual impact the church will have\n- Unity among all the churches involved\n- The community that will be served\n\n'We believe that prayer is the foundation of every great work of God,' said Grace Akello, youth fellowship leader. 'We are not just waiting for the adults to build this church. We are praying, we are giving, and we are declaring that this house will be filled with God's glory.'\n\nThe prayer walk concluded with a time of worship and fellowship at the construction site. Many young people also made commitments to give toward the building fund from their own pockets.\n\nThe WCCF leadership expressed deep gratitude for the youth's initiative. 'When the youth take ownership of this vision, we know the future is bright,' said Rev. Jane Smith.\n\nPrayer walks will be held on the first Saturday of every month. All are welcome to join.", 'excerpt' => 'Over 200 young people gather for a prayer walk around the mega church construction site.', 'author' => 'Grace Akello', 'category' => 'news', 'featured_image' => 'images/image-06.jpg', 'published_at' => '2026-06-02 16:00:00', 'is_featured' => false, 'is_active' => true]);
        Post::create(['title' => 'Meet the Construction Team Behind the Mega Church', 'slug' => 'meet-construction-team', 'content' => "As construction progresses on the WCCF Mega Church, we want to introduce you to the dedicated professionals who are turning this vision into reality. The construction team brings decades of combined experience in building churches, schools, and community facilities across East Africa.\n\nProject Manager: Eng. James Okello\nEng. Okello holds a Bachelor's Degree in Civil Engineering from Makerere University and has over 20 years of experience in large-scale construction projects. He has managed church construction projects in Uganda, Kenya, and Tanzania. His philosophy: 'Build with integrity, build to last, and build for God's glory.'\n\nLead Architect: Mr. Michael Ochieng\nMichael is a registered architect with the Uganda Society of Architects. He designed the mega church with a blend of modern and African architectural elements. The sanctuary features a distinctive cross-shaped roof structure visible from miles away.\n\nStructural Engineer: Eng. Grace Nabatanzi\nGrace is one of Uganda's leading structural engineers, specializing in seismic-resistant design. She ensures that every column, beam, and foundation meets international safety standards.\n\nSite Supervisor: Mr. Charles Odongo\nCharles is on site every day, coordinating the work of over 80 construction workers. He ensures that the work stays on schedule, on budget, and to specification.\n\nWe are grateful for this talented team and ask you to keep them in your prayers as they work to complete this monumental project.", 'excerpt' => 'Meet the engineers, architects, and workers building the WCCF mega church.', 'author' => 'WCCF Communications', 'category' => 'project-update', 'featured_image' => 'images/image-07.jpg', 'published_at' => '2026-06-05 10:00:00', 'is_featured' => false, 'is_active' => true]);
        Post::create(['title' => 'Statement from WCCF Leadership on Construction Progress', 'slug' => 'leadership-statement-june-2026', 'content' => "Dear partners, member churches, and friends of WCCF,\n\nGrace and peace to you from our Lord and Savior Jesus Christ.\n\nWe write to update you on the progress of the Mega Church Building Project and to express our heartfelt gratitude for your continued prayers, support, and generosity.\n\nAs of June 2026, the foundation work is 60% complete. The excavation phase has been successfully finished, and we have begun pouring concrete for the foundation pillars. The work has been progressing smoothly, and we are on track to complete the first phase by March 2027.\n\nFinancial Update:\n- Total funds raised to date: UGX 550 million\n- Monthly partner pledges: 187 partners committed\n- Funds disbursed for construction: UGX 320 million\n- Remaining balance: UGX 230 million in reserve\n\nWe continue to appeal to the body of Christ to support this work. The scale of this project requires significant resources, but we serve a God who is able to do exceedingly abundantly above all that we ask or think.\n\nWe also want to address some questions we have received about the project timeline. While we are committed to completing the construction as quickly as possible, we are equally committed to ensuring the highest quality and safety standards. We will not cut corners or compromise on quality in order to meet arbitrary deadlines.\n\nIf you have any questions, please do not hesitate to contact our offices. We value your partnership and are committed to transparency in all our dealings.\n\nYours in Christ,\nBishop John Doe\nChairman, WCCF", 'excerpt' => 'Foundation work is 60% complete with UGX 550 million raised toward the UGX 5 billion goal.', 'author' => 'Bishop John Doe', 'category' => 'project-update', 'featured_image' => 'images/image-08.jpg', 'published_at' => '2026-06-10 08:30:00', 'is_featured' => true, 'is_active' => true]);
    }
}
